### ISSUE TITLE
Is the react-widgets dependency necessary?

### ISSUE THREAD

**Issue by SL-HectorRios** [jquense/react-widgets-moment-localizer#4]
Hi,

We are using `react-widgets 3.0.0-beta.1` and today when we ran npm install, `react-widgets-moment-localizer` broke our install.

We were able to narrow it down to the dependency of `react-widgets ^2.0`. We're wondering if the dependency is necessary?

Best,
h

**Comment by jquense** [comment]
yes it is, you shouldn't be using the module with 3.0.0 which  is why I added the dep range to ensure that as I prepare to release 3.0.0.

the beta already includes a moment localized you can read the docs(run them locally) or look at how the dev example is set up in the code base
